name: Assertions

on:
  pull_request:
    branches: [main, develop]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Update NPM
        run: npm i -g npm@latest

      - name: Install dependencies
        run: npm i --legacy-peer-deps

      - name: Lint scripts
        run: npx eslint '**/*.{js,ts,jsx,tsx}' --config=.eslintrc.js

      - name: Lint styles
        run: npx stylelint '**/*.{css,scss}' --config=.stylelintrc.js
